spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_operation_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  messages:
    basename: ValidationMessages

management:
  endpoints:
    web:
      exposure:
        include: beans